# Demonize Server
# options(servr.daemon = TRUE)
# Serve site:
# blogdown::serve_site()
# http://127.0.0.1:4321/

baseurl = "/"
languageCode = "en-us"
title = "Max's Blog"
theme = "blackburn"
author = "Max Carey"
copyright = "&copy; 2018. All rights reserved."
#canonifyurls = true
paginate = 10

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "A Personal Website and Blog to Showcase my Work"
  brand = "Max Carey"
  googleAnalytics = "UA-133769355-1"
  disqus = "maxcarey-info"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Code Notes"
    pre = "<i class='fa fa-code fa-fw'></i>"
    weight = 2
    identifier = "code"
    url = "/code/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 4
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 5
    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "@axme100"
  github = "axme100"
  stackoverflow = "axme100"
  linkedin = "max-carey-aaba07166"