---
title: "My MOOC Journey to prepare for a Career in Data Science and NLP"
author: "Max Carey"
date: '2019-07-11'
description: ''
slug: plan-to-become-data-scientist
tags: [MOOCs, Data Science, edX]
categories: []
topics: []
---

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  text-align: left;
  border: none;
  outline: none;
  transition: 0.4s;
}

/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
.active, .accordion:hover {
  background-color:  #336cff;
}

/* Style the accordion panel. Note: hidden by default */
.panel {
  padding: 0 18px;
  background-color: white;
  display: none;
  overflow: hidden;
}

</style>



<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>

The purpose of this blog post is to plan for and document the steps that I am currently undertaking to prepare for a career in data science and/or computational linguistics. I have a background in academic linguistics: sociolinguistics, Spanish linguistics, applied linguistics (you can see my CV here). I **love** these fields and enjoyed teaching English and Spanish (applied linguistics) for a number of years. However, jobs in academia are quite scarce these days, so my ultimate goal is to find a job in industry where I can combine my love for language and linguistics with technology.

Fortunately, a lot of the skills I picked up in linguistics, like data analysis with R, are useful for a career data science and computational linguistics. I thought I would nerd out on a roadmap of my current MOOC journey to retool for a career these fields. My plan is to use this blog to keep track of my progress, stay motivated, take notes, show off my learning progress to potential employers, and hopefully, inspire others to follow a similar path. Of course, I will also be codecrastinating around with html-css-javascript (just for fun)! If you have any comments, thoughts, suggestions, please use Disques at the bottom of the page.

# Step 1: Refresh and upgrade math and statistics knowledge

I have had some college-level training in algebra, precalculus, calculus, and statistics, however, I only took 1 class in each field, and the classes were designed for business majors which meant they lacked certain topics, especially revolving around trigonometry.

## Step 1a) Comprehensive Algebra and Precalculus Review

$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}$$

The first step in my plan is to brush up on algebra and precalculus, using EdX classes. The great thing about these courses is that they use ALEKS, an online learning platform that uses an AI algorithm to predict what you already know and give you an individualized path to mastering the content. <a href="https://sway.office.com/tFxqIGwGLW6DmseU" target=blank> This blog </a> explains the pros and cons of Khan Academy vs. ALEKS, arguing that Khan academy is better because of the superior gamification and positive user reinforcement built into the platform. However, for people like me, adult learners, whose interest and commitement in math waxed and waned throughout high school and college, I mastered certain topics but always had certain holes in my knowledge. I think the <a href="https://www.aleks.com/video/how_aleks_works" target=blank>AI behind ALEKS</a> will really help me focus on the things I don't already know and learn the content faster, Khan academy doesn't create an individualized path for each learner (at least not that I know). Anyway, ALEKS let's you click on a button to watch videos for certain topics when you get stuck, some of which are Khan Academy, and others are from Arizona State University, the institution behind the MOOCs:

1. <a href="https://www.edx.org/course/college-algebra-problem-solving-asux-mat117x" target=blank> College Algebra and Problem Solving</a>
 <div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:100%">
    100%
  </div>
</div>
Arizona State University - MAT117


2. <a href="https://www.edx.org/course/precalculus-asux-mat170x" target=blank>Precalculus</a> 
<div class="progress">
  <div class="progress-bar progress-bar-striped active progress-bar-animated active" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:89%">
    89%
  </div>
</div>
Arizona State University - MAT170

## Interesting take-a-ways, counterintuitive ideas, subtelties

<button class="accordion">1. Factoring a quadratic with a leading coeficient greater than one using the grouping method</button>
<div class="panel">
  <p>Lorem ipsum...</p>
</div>

<button class="accordion">2. Transforming functions seems counterintuitive, especially shrinking and strething</button>
<div class="panel">
  <p>Lorem ipsum...</p>
</div>

<button class="accordion">3. Don't spend time memorizing facts about trigonometry</button>
<div class="panel">
  <p>In taking these classes, the hardest topic for me was trigonometry, especially things related to the unit circle. I remember in high school we were told to memorize the unit circle, in fact the precalculus course essentially memorizes that you memorize the coordinates on the unit circle as well. Memorzing things are the antithesis to conceptual understanding, I came across this video which gives a strategy for deriving the unit circle coordinates from 45-45-90 and 30-60-90 triangles. It took me a couple of hours to get this technique down, but I'm glad I invested the time, because now I am able to derive the unit circle from scratch, leading to a more intuitive understanding of trig functions. </p>
<br>
Trigonometric identies also seem to have a lot of things one needs to memorize. I found this great website which gives some advice on memorizing the pythogarean identies: https://www.mathbootcamps.com/the-pythagorean-identities-you-only-need-to-memorize-one/
<br>
This is a good video that explains trig vidoeos
https://www.youtube.com/watch?v=cS53LLKJdZo

</div>


https://www.youtube.com/watch?v=KFlFr7PJ4OA

https://www.youtube.com/watch?v=srj8b-RlXeg


https://www.youtube.com/watch?v=Wi0W_SbPTZs







https://www.youtube.com/watch?v=NxpXKiFjXjc

In general I think this is a good site to follow: https://www.youtube.com/channel/UC59w9x18hNNELpDvmo1UhVQ

## Step 1b): Calculus

The next step is to take calculus classes. In college, I took a business calculus class, and loved it. However, it was only a 10-week course that focused mostly on derivatives (we only looked at integrals for 1 week). I can see that calculus is quite important for data science, according to <a href="https://towardsdatascience.com/mathematics-for-data-science-e53939ee8306" target=blank>this blog:</a>

> "[Calculus is] used in machine learning (&deep learning) to formulate the funcions used to train algorithms to rech their objective, known by loss/cost/objective functions"


I have also heard that integrals are key to understanding probability. Also, it looks like most people pursuing a B.S. need to have 3 foundational courses in calculus before moving on to more advanced topics. I am really excited to see that MIT offeres just this content on edX:

Priority:

1. <a href="https://www.edx.org/course/calculus-1a-differentiation-2" target=blank> Calculus 1A: Differentiation</a>
 <div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:1%">
    0%
  </div>
</div>

To Be Completed Later:

2. <a href="https://www.edx.org/course/calculus-1b-integration-2" target=blank> Calculus 1B: Integration</a>
 <div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:1%">
    0%
  </div>
</div>


3. <a href="https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-series-2" target=blank> Calculus 1C: Coordinate Systems and Infinite Series</a>
 <div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:1%">
    0%
  </div>
</div>


4. Class in multivariate calculus, TBD

## Step 1c): Probability and Statistics Classes
The first class looks a bit easier and since it only requires derivatives and basic python programming, I plan to take it as soon as I finish my first calculus class mentioned above (the priority). The second class looks a bit more comprehensive as it requires derivatives, inegrals, infinite series, and multivariate calculus, I plan to take this class later, after finishing the single variable caclulus series and finding a multivariate calculus class.


1. Computational Probability and Inference
https://www.edx.org/course/computational-probability-and-inference

2. Probability - The Science of Uncertainty and Data
https://www.edx.org/course/probability-the-science-of-uncertainty-and-data-2


## Step 1d): Linear Algebra Classes
This class looks really cool and it's built by a guy who has been developing linear algebra educational software!

1. Linear Algebra - Foundations to Frontiers
https://www.edx.org/course/linear-algebra-foundations-to-frontiers-2

## Step 2: Upgrade Computer Science Knowledge, focusing particularly on data strcutures and algorithms class
Becoming a data scientist and or computational linguist requires knowledge of computer science theory, especially data structures and algorithms. Previously, I completed two intro-level CS classes at South Seattle Community College, which should prepare me to dive into the following classes:

1. Algorithmic Design and Techniques
https://www.edx.org/course/algorithmic-design-and-techniques

2. Data Structure Fundamentals
https://www.edx.org/course/data-structures-fundamentals

## Step 3: Bootcamp for funcional python coding ability and breaking into industry.
People have mixed feelings about bootcamps. I have heard a lot of people say how grads often lack either comprehensive theoretical knowledge (the point of taking all the previously mentioned prerequisites) or functional coding abilities.


## Step 4: Get Job in Mexico City
People who work in technical careers have often advised me that getting your foot in the door is one of the most important steps.

## Step 5: Continue developing knowledge of machine learning and AI techniques

## Step 6: Computational linguistics courses

1. Certificate in Natural Langauge Technology
https://www.pce.uw.edu/certificates/natural-language-technology
2. Master of Science in Computational Linguistcs
https://www.compling.uw.edu/

## Other resources:
1. https://medium.com/better-programming/the-data-science-interview-study-guide-c3824cb76c2e
2. https://realpython.com/data-science-podcasts/



<script>

var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    /* Toggle between adding and removing the "active" class,
    to highlight the button that controls the panel */
    this.classList.toggle("active");

    /* Toggle between hiding and showing the active panel */
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
} 

</script>