---
title: "Using Weave to Render UNAM Thesis in Latex with R Studio"
author: mc
date: '2018-11-25'
slug: test
categories: []
tags: []
description: 'How to typeset your UNAM thesis in LATEX through Weave in R Studio'
topics: [tesis, unam, spanish, biblatex, knitr, rstudio]
type: 'post'
---


At first my plan was to use R Markdown files and knitr to generate a PDF of my thesis. However, after researching different latex packages for bibliography management, I learned that the most actively developed and customizable programs was biblatex (not natbib) and biber (not bibtex). These programs seemed to work better for the kind of APA-based, Mexican Spanish bibliography that I needed.<a href="https://tex.stackexchange.com/questions/25701/bibtex-vs-biber-and-biblatex-vs-natbib/25702">This Stack Overflow post</a> explains these programs as well as their pros and cons.

More specifically, I found it difficult to configure the YAML header to meet these needs, it seemed like using raw latex preamble would be easier, plus most of the information on Stack Overflow about how to create APA bibliographies in Mexican Spanish didn't assumed peoplep were using YAML headers in R studio. But if I abandoned R markdown I couldn't have a reproducible document (or it would be much harder)!. Then I discovered weave! It looks like it looks like it is a way to intersperse R code with raw latex, in the end it avoids YAML headers and Pandoc giving you much more custom control of latex. <a href="https://kevinstadler.github.io/blog/knitr-rmarkdown-flavours/"> This page </a> explains the difference between .Rnw (weave) files and .Rmd (R markdown files).

When rendering a weave document in R studio, it appears I have to explcitily tell R studio that I want it to use biber, so I had to render the documents in the R console with the following command:

```{r eval=FALSE}
knitr::knit2pdf('testsweave.Rnw', bib_engine = "biber")
```


General Resources:
https://bookdown.org/yihui/rmarkdown/pdf-document.html
It looks like this page talks about overall document structure

## 1. Compiler
asdf
**pdflatex** (maybe xelatex)

- It looks like the default for overleaf and for R studio is pdfLaTex but XeLaTex can also be used for both. Xelatex may be better for certain unicode fonts, but I'll probably want to stick with the default, and just change the language to Spanish.
https://bookdown.org/yihui/rmarkdown/pdf-document.html


## 2. Citation package manager

**Biblatex**

- Looks like it can be used for Spanish quite well, see the code in this answer,
for the code that would need to be in the latex preamble (remember YAML hearders can also contain certain options options)
https://tex.stackexchange.com/a/321975/151573


- Better than apacite for Spanish:

> Since this is for a thesis (and the apacite package is not being required by a particular journal) you might also consider using biblatex and the biblatex-apa package, which is a very up-to-date implementation of the APA 6th edition. There are plenty of examples of its use on the site. (https://tex.stackexchange.com/a/37046/151573)

- Consider also **natbib** this is the package used by the template at ingeniería lingüística template (see below):

## 3. Document structure

- **Child = option in R markdown chunks** 
Doing this will allow chapters to be stored in separate Rmd Files
https://tysonbarrett.com/jekyll/update/2018/02/11/r_dissertation

## 4. Portada
- Looks like IIL has a template which is part of CTAN.ORG: (https://ctan.org/pkg/unamthesis?lang=en)
- https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=2ahUKEwjeztfAzankAhVHQ6wKHWtSCnIQFjADegQIAhAC&url=http%3A%2F%2Fwww.corpus.unam.mx%2Fcursolatex%2FUNAMThesis.tex&usg=AOvVaw1bEe8-okoNDFz2ZtOMHSkq
- Notice that it doesnt use biblatex
- https://tex.stackexchange.com/questions/234265/unam-thesis-title-page-portada-tesis-unam
- https://github.com/Tepexic/Tesis-UNAM
- https://www.overleaf.com/latex/templates/tesis-unam/vfwcjxnnwkdk